project:
  type: website

website:
  title: "Mehrin Kiani"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mehrinkiani
      - icon: twitter
        href: https://x.com/KianiMehrin
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

